### ISSUE TITLE
PR: Use electron-compile for main process/native deps

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#1039]

**Comment by develar** [comment]
Doesn't make sense. https://github.com/electron/electron-compile/issues/221 As far I known web pack approach used in this project is better. No need to use electron-compile — no advantages.

**Comment by amilajack** [comment]
@develar Thanks for the feedback on this. In that case, we'll stick with webpack

**Comment by aguynamedben** [comment]
That thread on electron-compile is extremely interesting. I would say there are tradeoffs, as well documented in that thread.

A problem I'm running into with the Webpack+Electron approach is finding a reasonable solution for pushing CPU-heavy work to a 3rd process. What is the recommended way to do that? I've done the DIY approach of spinning up a 3rd process myself and communicating to it via rpc/gRPC, but my solution isn't as elegant as [https://github.com/electron-userland/electron-remote](electron-userland/electron-remote). I haven't been able to get electron-remote working with this boilerplate due to issues with Webpack stomping on require.resolve(), and, after fiding that, the getting the development DLL to load correclty in electron-remote's BrowserWindow.

I'm curious for my own project, how much do you think it would be be to move a project based on this to electron-compile/electron-forge?

### Pros of electron-compile
1. Better support for dependencies like electron-remote that assume a pure Node.js environment.
1. Better support for electron-remote provides a "best practice" electron-react-boilerplate can recommend for pushing work to a 3rd process. Currently there is no recommendation.
2. Aligns your app with the way @MarshallOfSound (Atlassian) and @paulcbetts (Slack) do things.
3. Much simpler for the non-Webpack initiated. Simplicity is important.

### Cons of electron-compile
1. Slower development loading, but you [still have HMR](https://github.com/electron-userland/electron-compile#live-reload--hot-module-reloading).
2. Potentially slower production loader, but can be mitigated with the [V8 snapshots approach Atom takes](http://blog.atom.io/2018/01/10/the-state-of-atoms-performance.html).

### Not sure
1. I'm not sure if electron-forge is any better than electron-builder. electron-builder has been fine for me. I'm not sure if using electron-compile necessitates electron-forge.

I'm curious what y'all think, or if your thinking on this has evolved in the past year. Thanks for the work you put into this boilerplate.
