### ISSUE TITLE
BUG: Webpack freezes at "91% additional asset processing"

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#1045]
Is anyone else experiencing this?

Here's [a related issue](https://stackoverflow.com/questions/44262609/webpack-frozen-during-91-additional-asset-processing).

A temporarily solution i found was to comment the `devtool` webpack property in both production webpack configs.

Solution: try using uglifyjs or commenting babili in the webpack config

**Comment by uppe-r** [comment]
This happened to me before when I was trying to get monaco-editor to work with my project. Can't reproduce it now, though. I'll see if I can reproduce it later.

**Comment by amilajack** [comment]
@uppe-r what are your electron, npm, node, and electron-builder versions?

**Comment by uppe-r** [comment]
I still can't reproduce it, but at the time I had it failing my electron was on 1.6.2, Node on v6 (probably) and electron-builder on 16.6.0

**Comment by krispy-uccello-ck** [comment]
I am currently experiencing this issue and have been for a little while. Since I was just running dev builds I was manually exiting the process with a "ctrl-c" - I was then able to run the current state with npm run dev just fine. Now that I am trying to package - this has become a bigger issue for me. I will try the devtool: 'eval' approach and see where that leads.

**Comment by krsjoseph** [comment]
I tried adding the `devtool: 'eval'`  to my config, it no longer hangs but when the package is done i get this error
<img width="584" alt="screen shot 2017-06-15 at 5 58 15 pm" src="https://user-images.githubusercontent.com/1019869/27204361-b146faac-51f8-11e7-90a1-aaf2bfecfbda.png">

**Comment by amilajack** [comment]
Comment the `devtool: eval` line.

**Comment by uppe-r** [comment]
I ended up commenting Babili, seems like changing devtool to eval is not the best (production-wise), even though it worked for me.

**Comment by brandonmp** [comment]
I hit this awhile ago & commented-out babili. At the time I remember assuming it had something to do with babel relay but I don't think I ever pinpointed the cause. 

in my case it's just the renderer build that's broken, if that's at all helpful

**Comment by brandonmp** [comment]
quick update:  adding `--max-old-space-size=4076` to the `build-renderer` command seems to make babili work (albeit after a _long_ hang @ 91%)

eg
`"build-renderer": "cross-env NODE_ENV=production node --max-old-space-size=4076 --trace-warnings ...`

**Comment by SelaO** [comment]
Do you add that to the root webpack config object? 

Like so?

```
module.exports = {
  "build-renderer": "cross-env NODE_ENV=production node --max-old-space-size=4076 --trace-warnings",
  devtool: 'eval',
```

**Comment by ramsunvtech** [comment]
Below settings helped me to reduce the heap memory since it will not include the sourceMap file.

```
devtool: false, // Webpack.

new webpack.optimize.UglifyJsPlugin({
   sourceMap: shouldUseSourceMap
}),
```

or below code will help for latest webpack uglify plugin.

```
> npm install uglifyjs-webpack-plugin --save-dev

// conf.js
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
module.exports = {
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        sourceMap: true,
      }),
    ],
  },
};
```

If this still not help to fix the problem. below command helps to increase heap memory and answer link to know more about heap memory is below as well.

```
node --max-old-space-size=16000 scripts/build.js
```

https://stackoverflow.com/a/57480923/1533666
