### ISSUE TITLE
Having an issue with images showing up in packaged build (win10)

### ISSUE THREAD

**Issue by astralmedia** [chentsulin/electron-react-boilerplate#1293]
Hey, first off, thank you for all the hard work! This repo has been amazing in getting us off the ground.

I went thru all of the issues related to this, and tried everything I could find, but still cannot resolve the issue.

I just cloned the repo a few days ago, so the code is recent...but basically I am unable to see any of the images when in a packaged build.

I have my images in app/resources/images (also tried having the resources folder in the parent folder too, but no luck). In the code, I reference my images like so:

`<Avatar src="./resources/images/microdose_icon.jpg" />`

Not sure what to do here, any help would be amazing. Thank you again!

**Comment by amilajack** [comment]
I would recommend importing the image like so:
```js
import myImage from './images/my-image.jpg';

// ...
<img src={myImage} />
```

**Comment by cr05s19xx** [comment]
I realized that if you keep doing this, it converts the images into Base64 formats and uses it. Is that in any way better. Or do you think copying the images into a folder during the build process and referencing is a better option?

**Comment by cr05s19xx** [comment]
After much deliberation, I resorted to this solution:
The preamble to this solution is that:
- we use a copying webpack plugin (I chose [`copy-webpack-plugin`](https://github.com/webpack-contrib/copy-webpack-plugin))
- we place all the assets we want to reference into a folder, located in the root directory (we shall call it `extras`)

So, at first, in:
**`webpack.config.renderer.prod.js`**
```javascript
import CopyWebpackPlugin from 'copy-webpack-plugin';
...

export default merge.smart(baseConfig, {
   //  .... 

    plugins: [
        .... // Other plugins

        new CopyWebpackPlugin([
            {
                /*
                 * If an issue is to occur, it will probably be from here. This is because 
                 * I moved all the webpack configuration into its folder, so path 
                 * referencing could be an issue. But this example is with the assumption 
                 * that all the webpack configuration are in project root
                 */
                from: path.resolve(process.cwd(), 'extras'),
                to: path.join(__dirname, 'app', 'build', 'extras')
            }
        ])
    ]
});
```

Now after running the `npm run package` these files will be copied directly into an extras folder inside the `build` directory.

To use the files in both development and production, create a utilities file that will have the following functions. 
Note that you can place the file anywhere, since the build process compiles all the JavaScript into one file and so this won't be a problem.
**`app/utils.js`**
```javascript
import path, { sep } from 'path';
import fs from 'fs';

// Method returns the filepath for both development and production. Notice that in 
// production, we use the relative URL instead
export function getExtrasFolder() {
    return process.env.NODE_ENV === 'development'
        ? path.resolve(process.cwd(), 'extras')
        : path.resolve('./resources', 'app.asar', 'build', 'extras');
}

export function getExtraResource(folder, resourceName) {
    return path.resolve(folder, resourceName);

    // There is a redundant case where you wrap the return statement in a 
    //decodeURIComponent() method. I personally haven't come across a case where this is needed
}
```
