### ISSUE TITLE
history.push is not working?

### ISSUE THREAD

**Issue by marksalpeter** [chentsulin/electron-react-boilerplate#1399]
Hey guys. Here's what I'm trying to do in one of my components
```
...
componentDidUpdate(prev) {
    if (prev.isConnected && !this.props.isConnected) {
      this.props.history.push('/home');
    }
  }
...
````
I can't figure out why this isn't navigating to the home directory. I'm pretty new to react router redux. Any insights you have would be really helpful. Thanks

- Mark

**Comment by oussamajabnouni** [comment]
Same issue here

**Comment by oussamajabnouni** [comment]
Try this it worked for me

**Change routes order from**
```
  <App>
    <Switch>
      <Route path="/" component={LoginPage} />
      <Route path="/dashboard" component={DashboardPage} />
    </Switch>
  </App>
```

**to**

```
  <App>
    <Switch>
      <Route path="/dashboard" component={DashboardPage} />
      <Route path="/" component={LoginPage} />
    </Switch>
  </App>
```

**Comment by marksalpeter** [comment]
Thanks @oussamajabnouni, that worked!!

Does anyone have any idea why that worked?

**Comment by BuckyMaler** [comment]
Only a single route in a `<Switch>` will be rendered. That being said, order matters. React Router uses `path-to-regexp` to determine a path as a match or not. It's often recommended to put your paths in decreasing specificity because of the scenario you've encountered.

For example, `/home` will match `path="/"`. Therefore, you'd either want to change order as demonstrated by @oussamajabnouni or you can use the `exact` prop provided by React Router.

```
<App>
  <Switch>
    <Route exact path="/" component={Home} />
    <Route path="/other" component={Other} />
  </Switch>
</App>
```

Now, only `/` will match `path="/"` regardless of order.

[Route docs](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Route.md) and [Route Tester](https://pshrmn.github.io/route-tester/#/) are a couple of helpful resources for further exploration.

**Comment by mongodben** [comment]
You can also use the `exact` prop on the Route component to achieve the same functionality. 

See example here in the React Router DOM docs - https://v5.reactrouter.com/native/api/Route
