### ISSUE TITLE
packaging variables

### ISSUE THREAD

**Issue by mmahalwy** [chentsulin/electron-react-boilerplate#140]
I see we have checks for node_env to be development or not, but process envs don't get packaged in (for example, I packaged with production NODE_ENV). Thoughts about this?

**Comment by chentsulin** [comment]
That's why we only check `process.env.process === 'development'` now. If eventually we have to check something like: `process.env.process === 'production'`, we have to add some scripts into our build step.

It seems that you already find some good enough suggestions:
https://github.com/atom/electron/issues/4415  
https://github.com/maxogden/electron-packager/issues/259

**Comment by chentsulin** [comment]
The easiest solution I can find is that set default `NODE_ENV` to `production` at first line of `main.js`

`process.env.NODE_ENV = process.env.NODE_ENV || 'production';`

@mmahalwy What do you think?
