### ISSUE TITLE
App doesn't update properly after changing js in dev mode

### ISSUE THREAD

**Issue by gabriel** [chentsulin/electron-react-boilerplate#1400]
The app isn't updating properly in dev mode.

To reproduce:
(1) Checkout, `yarn install`, `yarn run dev`, and go to the app
(2) Select "to Counter" to go to the Counter view
(3) Edit `app/components/Counter.js` and change `odd</button>` to `odd2</button>`
(4) Save file

You'll see the app update but the button/link name doesn't change to `odd2`.

If you keep changing after a few times, the hot update starts working. It seems like when a full update happens, it doesn't actually update in the app (and is an update "behind").

**Comment by amilajack** [comment]
Which version of the boilerplate are you using?

**Comment by gabriel** [comment]
I reproduced it by checking out this repo's master.

**Comment by gabriel** [comment]
I checked it with v0.13.2 branch and was able to repro it. I made a video of what is happening here: https://temp-gbrl.s3.amazonaws.com/repro.mov

**Comment by gabriel** [comment]
This issue only reproduces with `yarn`. If I run with `npm` everything works ok.

Must be a dependency thing. I suppose could compare package lock file to json lock file to spot differences in dependencies?

**Comment by TheDolo** [comment]
I also have this problem!

**Comment by Cidolfas** [comment]
After a bit of digging I saw it recommended to try enabling "preserve log" in the dev console, and that does indeed give better messaging. When it does the full reload it gives these error messages:

`[HMR] Cannot apply update. Need to do a full reload!
module.exports../node_modules/webpack/hot/log.js.module.exports @ log.js:25
(anonymous) @ dev-server.js:34`

`[HMR] Error: Aborted because 0 is not accepted
Update propagation: 0
    at hotApply (http://localhost:1212/dist/renderer.dev.js:442:30)
    at http://localhost:1212/dist/renderer.dev.js:291:21
    at <anonymous>`

It looks like the common cause of this is not having HMR set up at the root node... but we have that set up and after a few loads it works correctly.

Any advice on where else to dig?

**Comment by kresli** [comment]
looks like removing `multiStep` from webpack config fix the issue 
```
 new webpack.HotModuleReplacementPlugin({
      // multiStep: true
    }),
```
