### ISSUE TITLE
Multi-window apps

### ISSUE THREAD

**Issue by davej** [chentsulin/electron-react-boilerplate#141]
My app has a preferences window which is separate to the main app window. I'm new to webpack so I'm wondering what's the best way to define a second potential entry point to the app?

**Comment by chentsulin** [comment]
see [webpack official document](https://webpack.github.io/docs/multiple-entry-points.html) and also discusses in https://github.com/gaearon/react-transform-boilerplate/issues/47

**Comment by davej** [comment]
Thanks!

**Comment by morajabi** [comment]
Another solution would be to use react router and have a separate route for each window, then it'd be easier to maintain.

More information:
e.g. adding Wrappers to the whole app at one instead of adding like Redux Provider in each module separately. I mean changing anything regarding the rendering logic.
