### ISSUE TITLE
Routes not working on production

### ISSUE THREAD

**Issue by cdiezmoran** [chentsulin/electron-react-boilerplate#1423]
I'm having trouble finding the source of this issue since I'm not getting any errors even when I package the app with `DEBUG_PROD=true`.  This works perfectly on development but here is how it looks on production:

![prodstandard](https://user-images.githubusercontent.com/13502661/36133986-8b90e15c-1047-11e8-95ea-7d8beed1a723.gif)

I've had issues like this for a little while and couldn't figure it out, today I updated to the latest version of the boilerplate and was able to fix a lot of them but I don't even know how to start on this one. I thought there was something wrong with the history or store but everything is getting passed correctly so it seems fine.

I don't think this is an issue with the boilerplate itself since it works with the counter example but maybe you can give me an idea to where I can start looking for the source of this issue. 

Thank you very much for your time in advance!

**Comment by BuckyMaler** [comment]
I'd be happy to help @cdiezmoran. It would be helpful if I could dig into the code on my local device. Can you provide the commands for me to clone the repo and start the app?

**Comment by cdiezmoran** [comment]
Thank you for the reply @BuckyMaler! Here are the commands to clone and start the app:
```
git clone https://github.com/cdiezmoran/AlphaStage-2.0.git alpha-stage
cd alpha-stage && yarn
```
And to start it on Prod you can do
```
DEBUG_PROD=true npm run package
or
DEBUG_PROD=true yarn start
```
You can log in using this credentials or create your own it is still using a development DB:
```
Email: test@example.com
PWD: password
```

**Comment by BuckyMaler** [comment]
@cdiezmoran your paths are updating as expected. You can see for yourself by logging `location` to the console when your app first loads, then navigate to the Dashboard and log `location` once more.

The issue you're having is termed, [updated blocking](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md), by React Router. React Router depends on the location object to determine what to render. In your case, the location object is updating as expected, but the React Router location-aware components are not re-rendering due to optimizations performed by React. The optimization that I believe is giving you trouble is `shouldComponentUpdate`, which is used by `react-redux`, [was](https://github.com/apollographql/react-apollo/issues/557) used by `react-apollo`, and is used by a number of other 3rd party libraries. In short, your `App` component is blocking updates.

There are a few solutions available, but the quickest is to use React Router's `withRouter` HOC like so:

```
import { withRouter } from 'react-router'

export default withRouter(connect(mapStateToProps, mapDispatchToProps)(App));
```

That should take care of your issue. Also, I suggest you use `createHashHistory` in your production store. I noticed it resolved 2 bugs rather quickly when I made that change. It resolved a window reload error, and the active menu item didn't appear active on initial load otherwise.

I recommend reading through [updated blocking](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md) if you need any further details as that documentation is well written.

I hope this helps. 😄

**Comment by amilajack** [comment]
@cdiezmoran Is your app open source? If not, is there a link to it's website if it has one? Would like to feature this app in the wiki somewhere

**Comment by cdiezmoran** [comment]
@BuckyMaler thank you so much for solving this issue! You have helped me a lot man thank you!

@amilajack Right now it is open to everyone on GitHub since it is not released yet but I haven't decided if I will go the open source route or not, the website is www.alphastage.gg and the repo is [here](https://github.com/cdiezmoran/AlphaStage-2.0). It means a lot that you want to feature it!

I'm closing this issue and thank you again!

**Comment by verdverm** [comment]
@BuckyMaler thank you so much for solving this issue! You have helped me a lot man thank you!

repo is here: https://github.com/verdverm/bastet

**Comment by Abhinay1235** [comment]
Try adding this to your package.json.  Set your base path.

'''"homepage": "https://example.com"'''

**Comment by pbbhopp** [comment]
Got the same issue with old version of serve. After update serve to the latest version(11.2.0 at that time), the Routes were ok.
