### ISSUE TITLE
Extra ./dist on asset files in prod

### ISSUE THREAD

**Issue by jbschrades** [chentsulin/electron-react-boilerplate#1426]
Hopefully this will help someone.  Or maybe someone can tell what I was doing wrong to begin with.  I have custom font files that were loading fine in dev.  In prod, however, styles.css was looking for the font files in:

```dist/dist/fontfilename.woff```

Changing this line:

https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.renderer.prod.js#L25

to 

```'publicPath: '',```

fixed the problem.

**Comment by thehatami** [comment]
@jbschrades
i clear it from L25, but still looking for /dist/dist/...

**Comment by aguynamedben** [comment]
This happened to me to and I don't understand why it was closed. I guess it's just stale.

I'll submit a branch from `master` that demonstrates it and a related pull request in a few minutes.

**Comment by aguynamedben** [comment]
I couldn't recreate this on master (2068ea0). My app is at 0.12 of this boilerplate. I thought this might be happening in my project because I hadn't incorporated recent Webpack 4 + mini-css-extract-plugin changes this project has implemented, but I implemented those changes in my project and the issue persists.

Changing to have `'publicPath: '',` as @jbschrades works, but I wish I knew why it's not working in some projects in the first place.

The only other major change I made to my project is I have multiple entry points:
```js
  entry: {
    renderer: [
      path.join(__dirname, 'app/renderer/index.js'),
    ],
    backend: [
      path.join(__dirname, 'app/backend/index.js'),
    ],
  },
  output: {
    path: path.join(__dirname, 'app/dist'),
    // This should be './dist/', I'm not sure why we need to make it '' for
    // custom fonts to load in prod
    // https://github.com/chentsulin/electron-react-boilerplate/issues/1426
    publicPath: '',
    filename: '[name].bundle.js',
  },
```
If anybody cracks this puzzle I am very curious!

**Comment by W1M0R** [comment]
I get the same issue in production if I make use of an `app.global.scss` (SASS) file, but not when I use an `app.global.css` file.

`webpack.config.renderer.prod.babel.js` has the following loader configuration for the `global.css` rule:

```javascript
{
 loader: MiniCssExtractPlugin.loader,
 options: {
   publicPath: './'
 }
},
```

But for the `global.scss` rule it is:

```javascript
{
 loader: MiniCssExtractPlugin.loader,
},
```

In other words, the global SASS rule is missing the `publicPath` option. After adding the same `publicPath` option to the `global.scss` rule, the issue was resolved for me.

**Comment by toioski** [comment]
@W1M0R you saved my day, thanks a lot!
