### ISSUE TITLE
Consider react-devtools plain shell?

### ISSUE THREAD

**Issue by davej** [chentsulin/electron-react-boilerplate#144]
Given that there are issues with the chrome devtools extension and electron (https://github.com/atom/electron/issues/915), perhaps it's worth considering the plain version? https://github.com/facebook/react-devtools/tree/master/shells/plain

**Comment by chentsulin** [comment]
Quite Interesting. Would you want to give it a try?

**Comment by davej** [comment]
Had a quick play around with this. It's not so easy because of the fact it uses an iFrame so it can't be easily integrated like the redux devtool component. You could do it with a `react-devtool-container-app.html` file which has an iframe pointing at `hot-dev-app.html`.

I'm not very fond of this approach though because my app is multi-window and it starts to get unwieldy very quickly if you want to have the devtools available on multiple windows.

Might give this another try in the future but I'm going to leave it for now.

**Comment by LongLiveCHIEF** [comment]
I looked through the source for this, and I don't think it would be too hard to modify what's there to create a new "shell/electron" based on what the shells/plain does.  Instead of postmessage api usage, you could use the ipc module, and instead of an iframe, you could use a <webview> tag.

I might give this a shot.

**Comment by chentsulin** [comment]
https://github.com/electron/electron/releases/tag/v1.2.1 fixed support for DevTools Extensions, so we can close this now.
