### ISSUE TITLE
How to change routes from the main process

### ISSUE THREAD

**Issue by juanda99** [chentsulin/electron-react-boilerplate#1485]
I want to change the current app route from the user menu. I guess it's quite common but couldn't find it in the docs.

Currently I've use loadURL, as I don't have access to React Router from the main process:
```
{
      label: '&Users',
      submenu: [{
        label: 'List',
        accelerator: 'Ctrl+R',
        click: () => {
          this.mainWindow.loadURL(`file://${__dirname}/app.html#users`);
        }
      }]
    }, 
```

It doesn't seem to be the proper way. I didn't see any info or code in the example. What is the proper way? Using IPC?

**Comment by nessup** [comment]
IPC is definitely the simplest route. Using react-router, the basic idea is

1. send a message from main to renderer with the URL you'd like to show
2. renderer receives the message and sets window.location
3. react-router responds to the change

Note that, in #2, you could use router navigation like `push()` and `replace()` rather than setting window.location if you want to control how the URL history is handled.
