### ISSUE TITLE
Console.log is swallowed in renderer

### ISSUE THREAD

**Issue by chthomos** [chentsulin/electron-react-boilerplate#1501]
It seems that plain console.log does not work in DEV environment. Redux-logger works fine, and I can see the state changes in console, but when I try to add a console.log, either in a component or in a generic class it's swallowed. 

Any ideas?

**Comment by nessup** [comment]
Redux-logger uses console.log, so hard to say. There's maybe an issue elsewhere.

**Comment by Slapbox** [comment]
Log level filtered in devtools? That's really all I can think of. This 100% definitely works in this boilerplate and every installation of it I have ever customized in any way.

**Comment by amilajack** [comment]
@chthomos are you still having this issue?

**Comment by symnetry** [comment]
i have same problem 
 `class Req{
test(arg){
console.log(arg)
return arg
}
}
const qq=new Req() console.log(qq.test('example'))`  then only console the ·return· arg

**Comment by Slapbox** [comment]
I strongly recommend [electron-log](https://www.npmjs.com/package/electron-log) to everyone, having this problem or otherwise.

Using Webpack to include that module in every file of your renderer means you can use `log.info()` instead of `console.log()` 100% effortlessly, and gain the additional benefits that it affords you as well, like logging to file.

If anyone has any questions about this method, I can reference my project for some code upon request.

**Comment by carlosgonzalezmendoza** [comment]
@Slapbox I'll take you on that offer! I'm looking to log to a file from both main and renderer. I'm using ERB. Do you have any examples I can take a look at? Thanks.
