### ISSUE TITLE
Invalid build for Windows

### ISSUE THREAD

**Issue by josephbuchma** [chentsulin/electron-react-boilerplate#1574]
Steps to repro (*on Linux*):
1. clone this repo
2. `npm install`
3. `DEBUG_PROD=true npm run package-win`
4. Instal and run on Windows from command line, this is output:
```
{ Error: spawn C:\Users\Joseph\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\7zip-lite\7z.exe ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn C:\\Users\\Joseph\\AppData\\Local\\Programs\\electron-react-boilerplate\\resources\\app.asar\\7zip-lite\\7z.exe',
  path: 'C:\\Users\\Joseph\\AppData\\Local\\Programs\\electron-react-boilerplate\\resources\\app.asar\\7zip-lite\\7z.exe',
  spawnargs:
   [ 'x',
     'C:\\Users\\Joseph\\AppData\\Roaming\\electron-react-boilerplate\\extensions\\fmkadmapgofadopljbjfkapdkoienihi.crx',
     '-y',
     '-oC:\\Users\\Joseph\\AppData\\Roaming\\electron-react-boilerplate\\extensions\\fmkadmapgofadopljbjfkapdkoienihi' ] }
```

**Comment by jdpigeon** [comment]
Getting this problem too on a real Windows 10 machine

**Comment by kiddailey** [comment]
Just saw an email notification that this was closed.  Was watching the issue because I also have experienced the same problem.  I assume it has to be reopened for consideration now?

**Comment by jdpigeon** [comment]
The issue for me, it turned out, was that 7zip wasn't installed and accessible by Node through my Windows environment variables.

After installing 7zip and putting it in PATH the problem has gone away.

https://github.com/quentinrossetti/node-7z/issues/25

**Comment by amilajack** [comment]
<img width="720" alt="screen shot 2018-09-19 at 1 59 36 pm" src="https://user-images.githubusercontent.com/6374832/45781262-54a0eb00-bc14-11e8-8f60-a06dc4517976.png">

**Comment by kiddailey** [comment]
@jdpigeon - That's interesting.  I have 7zip installed but I don't believe it's in my path.  Will give that a try and see if it resolves the issue.  Do you have any native dependencies in your app?

@amilajack - Not sure I follow your post.  In my case, this issue was occurring on a single platform.  It compiles and runs correctly unless you set the DEBUG_PROD flag

**Comment by jdpigeon** [comment]
Yes, my app uses native dependencies. I hope that 7zip fix helps!

@amilajack was pointing out that, if you're using native dependencies, you shouldn't expect to be able to build your app for different platform than the one you're developing on (e.g. building for Windows on Linux like the OP). AFAIK, this isn't due to anything specific with this project, but is just generally a limitation of node's native tooling in general.
