### ISSUE TITLE
Removal of font-awesome npm package

### ISSUE THREAD

**Issue by gorilla-devs** [chentsulin/electron-react-boilerplate#1623]
I would suggest to remove the font-awesome npm package in favour of the import in the app.html like this: 

`    <script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js" integrity="sha384-3LK/3kTpDE/Pkp8gTNp2gR/2gOiwQ6QaO7Td0zV76UFJVhqLl4Vl3KL1We6q6wR9" crossorigin="anonymous"></script>
`

This is because the npm package is outdated (2 years old) and not updated to font-awesome v5.
If accepted i can do a PR for this

**Comment by amilajack** [comment]
The nice thing about using the npm package version is that the user of the app doesn't need to have network access to open the app. Is there any way to install from `fontawesome`'s source?

**Comment by gorilla-devs** [comment]
IDK about that but a workaround could be to include the css file of fontawesome packaged with the boilerplate. This way it could be updated from time to time directly in the boilerplate or from the user

**Comment by uppe-r** [comment]
It actually seems like they made a different npm package since there is now a pro/free version: [https://www.npmjs.com/package/@fortawesome/fontawesome-free](https://www.npmjs.com/package/@fortawesome/fontawesome-free), as shown in [https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers](url)

So really just a change in package.json and maybe the file path in the css file would do it.
