### ISSUE TITLE
Use electron-builder to pack app

### ISSUE THREAD

**Issue by xwartz** [chentsulin/electron-react-boilerplate#209]
[electron-builder](https://github.com/electron-userland/electron-builder#readme): 
Complete solution to build ready for distribution and "auto update" installers of your app for OS X, Windows and Linux.

And this is my project example with `electron-builder` - [douban.fm](https://github.com/xwartz/douban.fm)

**Comment by chentsulin** [comment]
Would you want to prepare a PR?

**Comment by xwartz** [comment]
ok, I will give it a try.

**Comment by burkhardr** [comment]
@xwartz Any progress on this at all?

**Comment by xwartz** [comment]
Hi @burkhardr , sorry, I don't have windows device for testing. 

And It's difficult to express with my poor English. So i hope somebody to take over it.

**Comment by dustintownsend** [comment]
I took a crack at this, but had to change the structure of the app to get it all working. I used @xwartz project example.

Electron-builder defaults to using an 'app' folder to build to (so the 'dist' folder in the boilerplate). And the application source files in an 'src' folder. It also has two package.json files, one for development and one for application. I think due to my lack of knowledge on webpack I'm missing something with that step and ended up with duplicate dependencies to get it to build. In @xwartz project there were no dependencies in the application package.json.

To do:

- [ ] figure out how to manually load dependencies from the application package.json for webpack building.
- [ ] revert the paths to the boilerplate default (need to figure out how to override these settings in electron-builder). 

https://github.com/dustintownsend/electron-react-boilerplate/tree/electron-builder

**Comment by xwartz** [comment]
Hi,  @dustintownsend 

1. No need to do this. You can set webpack config [output](http://webpack.github.io/docs/configuration.html#output) to 'app' folder. So no need to load  dependencies from application package.json.

2. The [docs](https://github.com/electron-userland/electron-builder#two-packagejson-structure) dosen't figure out how to override these settings.

**Comment by amilajack** [comment]
We have an initial working version under review at the moment

**Comment by Slapbox** [comment]
@amilajack Any update on that? That would be a huge leap forward for the boilerplate.

**Comment by amilajack** [comment]
I'm actually testing it as i type this 😂

**Comment by Slapbox** [comment]
Awesome, thanks for the update. I'm struggling to get my own implementation of it working now. Looking forward to the new release and thanks for the great work.

**Comment by amilajack** [comment]
@Slapbox unfortunately I don't have permission to make releases on `npm`. Its up to @chentsulin

**Comment by Slapbox** [comment]
Gotcha, thanks for the update.

Can I ask you, did you run into any issues with blank windows after running the exe put out by electron-builder? I don't even get a menu bar up top. I actually get closer running the source code through electron-builder than I do when I run through the bundle.js.

**Comment by amilajack** [comment]
@Slapbox actually I didn't even do most of the work on the `electron-builder` PR. I just fixed the merge conflicts and tested it. When testing it, I didn't experience anything like that.

**Comment by Slapbox** [comment]
Ah alright. I feared that would be your answer lol.

In the interim, is there anywhere I can view the code you're working on? I know I'm just on the cusp of getting it working, and I can't find what I'm overlooking. I'm thinking it's something pretty simple since I spent all day hammering out the larger issues. If not though, I'll be eagerly awaiting and hoping that the new code gets integrated. Thanks Amila!

**Comment by amilajack** [comment]
@Slapbox Its was merged a few minutes ago

**Comment by Slapbox** [comment]
Haha wow this has been quite a serendipitous exchange. Thanks again for all your good work.

**Comment by amilajack** [comment]
Np. I would recommend waiting for https://github.com/chentsulin/electron-react-boilerplate/pull/491 to be merged. It fixes a few `gitignore` changes that I overlooked while reviewing.

**Comment by TimoSolo** [comment]
Is this merged now? How do I use the auto-updater?

**Comment by amilajack** [comment]
The auto-updater functionality has not been added yet: https://github.com/chentsulin/electron-react-boilerplate/issues/504
