### ISSUE TITLE
"npm run package" error

### ISSUE THREAD

**Issue by jolic** [chentsulin/electron-react-boilerplate#235]
Got this error:

```
$ npm run package

Downloading electron-v1.2.0└─┬nightmare@2.5.0└──-darwin-x64.zip
Error: GET https://github.com/electron/electron/releases/download/v1.2.0└─┬nightmare@2.5.0└──/electron-v1.2.0└─┬nightmare@2.5.0└──-darwin-x64.zip returned 400
Error: GET https://github.com/electron/electron/releases/download/v1.2.0└─┬nightmare@2.5.0└──/electron-v1.2.0└─┬nightmare@2.5.0└──-darwin-x64.zip returned 400
....
```

Any hints on this? Thx.

**Comment by chentsulin** [comment]
It's likely a problem with github (send GET request but return status code 400). Maybe everything will works after a retry.

You can use `electron-download` to test whether you can properly download electron or not. If it doesn't work for you, open an issue there:
https://github.com/electron-userland/electron-download

**Comment by vinnymac** [comment]
@jolic @chentsulin  I had this problem also. It looks like when using electron-react-boilerplate the logs sometimes show dependencies in the downloading log, whereas if we use electron-download you get something along the lines of `Downloading electron-v1.3.5-win32-ia32.zip` instead.

Apparently the reason this is happening is because of [this line](https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.js#L55).

If we have a dependency tree that returns this in `stdout`, when you go to package your app you will end up trying to download the wrong electron version.

In my case I was downloading electron with the version `1.3.5└─┬electron-rebuild@1.2.1└──` which obviously does not exist, and returns a 400.

The code on that line assumes that prebuilt will only appear once in the string when it splits. In my case the string it was splitting looks like below.
```javascript
"├── electron-prebuilt@1.3.5└─┬ electron-rebuild@1.2.1└── electron-prebuilt@0.36.12".split('electron-prebuilt@')
// ["├── ", "1.3.5└─┬ electron-rebuild@1.2.1└── ", "0.36.12"]
```

So as the output of npm list changes or the dependencies in your project change, package.js becomes more fragile. I think this needs to be patched, either improving the parsing logic or creating an alternative way of retrieving prebuilts version would be decent solutions.
