### ISSUE TITLE
electron-react-boilerplate calling electron api

### ISSUE THREAD

**Issue by Sieryuu** [chentsulin/electron-react-boilerplate#619]
```
// @flow
import React, { Component, PropTypes } from 'react';
import { ipcRenderer, ipcMain, dialog } from 'electron'

ipcMain.on('open-information-dialog', function (event) {
  const options = {
    type: 'info',
    title: 'Information',
    message: "This is an information dialog. Isn't it nice?",
    buttons: ['Yes', 'No']
  }
  dialog.showMessageBox(options, function (index) {
    event.sender.send('information-dialog-selection', index)
  })
})

export default class App extends Component {
  static propTypes = {
    children: PropTypes.element.isRequired
  };

  handleClick() {
    console.log("test");
    ipc.send('open-information-dialog');
  }

  render() {
    return (
      <div>
        <button onClick={this.handleClick}>test</button>
        {this.props.children}
      </div>
    );
  }
}
```

Any idea whats wrong with my code? please help me :(

**Comment by amilajack** [comment]
Would be helpful if you could show the stack trace and describe the error more.

**Comment by Sieryuu** [comment]
@amilajack the ipcMain is undefined when assigning `on` event

**Comment by amilajack** [comment]
Please show the stack trace

**Comment by amilajack** [comment]
Also did you see this? http://stackoverflow.com/questions/33964864/electron-typeerror-in-ipcmain-event-handler

**Comment by dustintownsend** [comment]
@Sieryuu I am going to assume this is in the `Renderer` since it's a `React.Component`. If that is the case `ipcMain` can't be called from the `Renderer` process.

You should move the following to your main.developerment.js file:
```
import { ipcMain, dialog } from 'electron'

ipcMain.on('open-information-dialog', function (event) {
  const options = {
    type: 'info',
    title: 'Information',
    message: "This is an information dialog. Isn't it nice?",
    buttons: ['Yes', 'No']
  }
  dialog.showMessageBox(options, function (index) {
    event.sender.send('information-dialog-selection', index)
  })
})
```

Also, you should use `ipcRenderer.send` in your `handleClick` function.

```
  handleClick() {
    console.log("test");
    ipcRenderer.send('open-information-dialog');
  }
```

However, I believe that using `Remote` for this is now the recommended way. Or at-least my preferred way. It keeps all the logic together and avoids getting `ipcMain` vs `ipcRenderer` mixed up. There are still cases where using `IPC` makes sense, but I think for this case `Remote` is the way to go.

```
// @flow
import React, { Component, PropTypes } from 'react';
import { remote } from 'electron';

const dialogOptions = {
  type: 'info',
  title: 'Information',
  message: "This is an information dialog. Isn't it nice?",
  buttons: ['Yes', 'No']
};

export default class App extends Component {
  static propTypes = {
    children: PropTypes.element.isRequired
  };

  handleClick= () => {
    remote.dialog.showMessageBox(dialogOptions, (index) => {
      console.log('information-dialog-selection', index);
    });
  }

  render() {
    return (
      <div>
        <button onClick={this.handleClick}>test</button>
        {this.props.children}
      </div>
    );
  }
}
```

**Comment by dustintownsend** [comment]
@amilajack I think this can be closed, since it's not an issue with the boilerplate.

**Comment by Sieryuu** [comment]
thanks you very much for the answer @dustintownsend. it helps alot.

**Comment by RodPaDev** [comment]
I believe the use of `remote` should be documented since it's very possible to end up using native modules on the frontend. 
I would also like for future reference that on the newer versions of electron you need to add `enableRemoteModule: true` to `webPreferences` when instancing a new BrowserWindow.

```js
  mainWindow = new BrowserWindow({
    webPreferences: {
      nodeIntegration: true,
      enableRemoteModule: true
    }
  })
```
As seen on [Stackoverlow - Electron Remote Is Undefined](https://stackoverflow.com/questions/37884130/electron-remote-is-undefined)
