### ISSUE TITLE
Issue loading images in production package

### ISSUE THREAD

**Issue by ivtpz** [chentsulin/electron-react-boilerplate#712]
Hi,

I realise this issue has been referenced before, but I have tried the suggested solutions from [#250](https://github.com/chentsulin/electron-react-boilerplate/issues/250#issuecomment-227494838) and am still unable to load images when I package my app. 

I am accessing images in development two ways - both in CSS as follows: 

`background: url('../assets/image_to_load.png')`

and in my .js files like this: 

```
var Logo = require('../assets/48x48.png');
<img src={Logo} />
```

Both load fine on the dev server, but not in the production package. I tried `alert(Logo)` in dev and in production, and got 
`data:image/png;base64,iVBORw0KGgoA....` from the dev environment and 
`data:image/png;base64,bW9kdWxlLmV4....` in the prod package.

I have also tried using `import Logo from '../assets/48x48.png'`, and the production app errors out when it fails to find the images.

I am currently using `url-loader` in the webpack config for images. Any advice on how to proceed would be much appreciated. Thanks.

**Comment by remicoges** [comment]
I had the same issue as you and what I did is remove these lines from `webpack.config.production.js`

```
// Images
{
    test: /\.(?:ico|gif|png|jpg|jpeg|webp)$/,
    loader: 'url-loader'
}
```

**Comment by ivtpz** [comment]
Thank you @remicoges!! Solved my issue. Once I deleted those lines from production, and increased the limits on file sizes for the `url-loader` it worked. In case this is helpful to others down the road - I was not able to load images or custom fonts through `file-loader` in production, only `url-loader`.

**Comment by amilajack** [comment]
@ivtpz @remicoges Would appreciate a PR that adjusts the `webpack.config.production.js` so it can better suite other users!

**Comment by amorino** [comment]
url-loader won't work for json, mp3, mp4 video file. Is there any way we can use file-loader with this boilerplate?

**Comment by amilajack** [comment]
@amorino try adding those extensions to [this line](https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.development.js#L103)

**Comment by Moinax** [comment]
Why the file-loader cannot be used in production mode ?

**Comment by amilajack** [comment]
[We now use file-loader in production](https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.renderer.prod.js#L117)

**Comment by Moinax** [comment]
Ok, but how can we make it works for images on v0.10.0 ?

**Comment by amilajack** [comment]
https://github.com/chentsulin/electron-react-boilerplate#how-to-keep-the-boilerplate-updated

**Comment by Moinax** [comment]
Do you mean that if I merge your master in my code, I can put back the query?limit=10000 on the url-loader and get the file-loader working as expected when the limit is reached ?

**Comment by johannpinson** [comment]
Hi @amilajack 

I reading severals issues about "image loader" because actually the webpack configuration force url-loader (and so base64 for a lot of situation).
But I had a larger SVG file than 10Kb and in dev run the relative path was well, in production package (with `npm run package`), we got a 404. So I remove the limit.

But next, I had to add .stl files for WebGL (with Three.js inside React) and had this configuration to renderer.prod and dev :
```
// WebGL Files
{
  test: /\.stl(\?v=\d+\.\d+\.\d+)?$/,
  use: 'file-loader'
}
```

In "dev" mode it's working, but not in "prod" (with `npm run start`) or package installed.
So I test this
```
import obj from '../assets/models/obj.stl';
...
console.log(obj);
```

In dev i see `http://localhost:1212/dist/af7ae505a9eed503f8b8e6982036873e.stl`

In other case (production package and from .exe) i see `../dist/af7ae505a9eed503f8b8e6982036873e.stl`
I also have this error in ChromeDevTools :
`GET file:///C:/dist/af7ae505a9eed503f8b8e6982036873e.stl net:ERR_FILE_NOT_FOUND`

I don't know why but React try to load the file from the root path and not the relative (like in CSS or in HTML file).

I also test with an image and `file-loader`like :
```
import myImage from '../assets/test.jpg';
...
render() {
  return (
    <div>
      <img src={myImage} alt='test' />
    </div>
  )
}
```
And then, also the same bug, it's work in dev mode, but not in production.


Thanks for your help!

**Comment by amilajack** [comment]
@johannpinson This use case seems complex. Would be easier for me if you could create a fork of the boilerplate and make the minimal amount of changes to reproduce this bug

**Comment by DarioN1** [comment]
Any news ?

**Comment by amilajack** [comment]
No news on this just yet. I'll try to create a fork of the boilerplate that demos this feature.

**Comment by mlukasch** [comment]
Have the same issue.

**Comment by guruprasaad123** [comment]
use `url-loader ` instead of the ` file-loader ` .This resolved my Issue @mlukasch
