### ISSUE TITLE
Unexpectingly big package size

### ISSUE THREAD

**Issue by lightningboss** [chentsulin/electron-react-boilerplate#795]
Hello,

when running `yarn run package` it outputs a `.app` that is 113,8 megabyte big. I think this is way too much for such a simple application I am building.

My node_modules is about 330 megabyte big, all other source folders take some kilobyte.

What do you think is the cause? Is that something normal? What should be a normal file size?

**Comment by amilajack** [comment]
@lightningboss what are your node and npm versions? Try solution 3 in #400 and then try packaging again

**Comment by lightningboss** [comment]
Even though it reduced the size of my node_modules, it didn't reduce the size of the app. It is still 113,8 megabyte big.

npm: 3.10.9
node: 6.3.0

**Comment by amilajack** [comment]
Are you on mac or windows?

**Comment by dustintownsend** [comment]
I am not targeting mac, so can't speak to the size of the .app. But for Windows my win-unpacked folder is 153MB. I am thinking that the .app is not compressed.

The final installer for windows is around 35MB, but it will be unpacked on the PC and use 153MB.

The reason for this isn't your node_modules or your app. It is due to Electron. You have to keep in mind that you are shipping your app packaged with Chrome and Node.Js. For windows the electron exe is 85MB itself. There is about 130MB (including the 85MB) of files that are not my code.

Now if your `app.asar` file (under resources folder) is 113MB it would be due to your node_modules and js files. In my case it is around 20MB.

You can dig into `electron-builder` docs to look at options for compression. For example you can increase the compression of your `app.asar` file. It will increase the build time.
https://github.com/electron-userland/electron-builder/wiki/Options

**Comment by amilajack** [comment]
~113MB is the expected size. I'm going to PR to update the electron-builder config so that consumers of the boilerplate can have better build options like snap, portable windows images, etc

**Comment by bksubhuti** [comment]
My app is 600 mb with a browser.. but 5gb when I make a package.. why
![image](https://user-images.githubusercontent.com/18184280/87313608-20fd2680-c548-11ea-97db-93767dca60f2.png)

**Comment by TBG-FR** [comment]
> My app is 600 mb with a browser.. but 5gb when I make a package.. why. Made on linux.. with wine installed.. tested on win10
> 
> ![image](https://user-images.githubusercontent.com/18184280/87313608-20fd2680-c548-11ea-97db-93767dca60f2.png)

I am facing the same issue.  Do you have any copied folders (like copy of `dist`) in your project folder ? (=> https://stackoverflow.com/a/56497447/8179249). Removing these folder I made earlier solved it for me.
