### ISSUE TITLE
Bikeshed: Slack Channel for the Repo?

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#801]
Is there a Slack channel for the boilerplate? It might take some of the support load off of @amilajack which I bet he would appreciate.

**Comment by amilajack** [comment]
There is a gitter chat that we created a while ago. I think creating multiple channels would divide the small community that uses this boilerplate. Thoughts?

**Comment by Slapbox** [comment]
Ah I do vaguely recall the Gitter.

I think Slack is a lot better of a platform for collaboration/learning personally, and that it has an interface that is easier for people who have never used it to pick up than Gitter.

My personal opinion (emphasis on opinion) is that unless we have some people really attached to Gitter, it might make sense to forcibly change over to Slack. 

Slate.js by IanStormTaylor has a Slack and it's been working really well to bring new people up to speed and share findings/solutions. I can't imagine I'd have ever learned what I was doing without it.

**Comment by akozhemiakin** [comment]
I personally prefer Gitter or Discord over Slack. Particularly I do not like the fact that in Slack you must have separate account for every channel. Also React community uses Discord (in fact guys behind React were kind of forced to migrate from Slack to React some time ago: https://facebook.github.io/react/blog/2015/10/19/reactiflux-is-moving-to-discord.html)
Also I would probably choose Discord over Gitter because from my sight Gitter looks kind of stagnating and has multiple long standing problems, like search usability and poor mobile app for example.

**Comment by talha131** [comment]
No slack please. Exactly, for this reason

> I personally prefer Gitter or Discord over Slack. Particularly I do not like the fact that in Slack you must have separate account for every channel.

**Comment by Slapbox** [comment]
I'm not familiar with Discord, but am very underwhelmed with Gitter. Given the interest in Discord, I assume it would be a worthy alternative.

As @akozhemiakin points out, it feels like Gitter is not going anywhere, not improving, and not in anywhere near an ideal state right now.

**Comment by dustintownsend** [comment]
I think we should continue using Gitter. The barrier to entry is very low since you just need a Github account to login. Slack's model of a different login for each community might discourage people from using it. As @talha131 and @akozhemiakin mentioned.

@Slapbox I think a better thing to do would be identify what was it about Slate.js use of Slack that was so beneficial and try to apply that to Gitter the best we can. Do you think you could give Gitter another chance?

@akozhemiakin which mobile app are you using? I think the iOS app is good.

**Comment by Slapbox** [comment]
@dustintownsend Admittedly part of what makes the Slack channel for Slate.js so useful is that many people have questions on a regular basis, which means that the channel has people around pretty often.

That being said, the platform of Slack itself I feel just works better for the purpose at hand, which unfortunately isn't something we can port. One thing I find helpful for example is nested conversations, for lack of a better way to describe them. I'm not sure if you know what I mean by that.

If people want to stick with Gitter, I say stick with it. I'd personally favor moving to a different platform, but that only makes sense if we can bring along those who are currently using Gitter.

As I mentioned, all of the above is only opinion.

**Comment by akozhemiakin** [comment]
I use the one for Android. And it has "cool" futures like auto sending your messages even if you do not want to and it has not some features like editing capability. But actually I'm much more concerned about awful search interface on the website, for me it looks nearly unusable.  And good search is a big thing, because it allows users not to ask the very same thing again and again.

**Comment by Slapbox** [comment]
@akozhemiakin Search is a key point where I think Slack excels, however it only goes back 10,000 lines for the free version.

**Comment by Elyx0** [comment]
My 0.02$: Discord is definitely the way to go. Its search goes back to the beginning of time, plus given that this package is downloaded ~200times a month (and it will grow for sure) one gitter channel might be too crowded to handle the different conversations that would be going on. Whereas like Yarn, a Discord with #general, #support, #dev might be enough to get going.

**Comment by OlivierCo** [comment]
Hey guys I created a slack Team you will find it at [slatejs.slack.com ](https://slatejs.slack.com/messages)
please join it....
